apiVersion: v1alpha1
kind: Setting
metadata:
  name: blog-halo-theme-setting
spec:
  forms:
    - group: global
      label: 全局
      formSchema:
        - $formkit: text
          name: background
          label: 全局背景样式（对应 css 的 background 属性）
          placeholder: 如：#F9F8F7
          value: "#F9F8F7"
          validation: "required"
    - group: post
      label: 文章
      formSchema:
        - $formkit: select
          name: postListCardStyle
          label: 列表显示样式
          value: default
          id: postListCardStyle
          key: postListCardStyle
          validation: "required"
          options:
            - value: default
              label: 默认
            - value: left-img
              label: 左图右文
            - value: top-img
              label: 上图下文
        - $formkit: select
          if: "$get(postListCardStyle).value === 'left-img' || $get(postListCardStyle).value === 'default' "
          name: column
          id: column
          key: column
          label: 列表显示列数
          value: 2
          validation: "required"
          options:
            - value: 1
              label: 一列
            - value: 2
              label: 两列
        - $formkit: attachment
          if: "$get(postListCardStyle).value === 'top-img' || $get(postListCardStyle).value === 'left-img'"
          name: defaultCoverImg
          id: defaultCoverImg
          key: defaultCoverImg
          label: 文章默认封面
          placeholder: 文章默认封面
          value: ""
          validation: "required"
          accepts:
            - "image/png"
            - "image/jpeg"
            - "image/gif"
            - "image/webp"
            - "image/svg+xml"
            - "image/bmp"
            - "image/tiff"
        - $formkit: select
          name: showPostImgs
          label: 是否展示侧边图片
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: repeater
          name: postImgs
          label: 文章侧边图片（如：收款码、公众号等）
          value: []
          children:
            - $formkit: text
              name: label
              label: 图片名称
              placeholder: 如：微信赞赏码
              value: ""
              validation: "required"
            - $formkit: attachment
              name: img
              id: post_img_src
              key: post_img_src
              label: 图片地址
              placeholder: 图片地址
              value: ""
              validation: "required"
              accepts:
                - "image/png"
                - "image/jpeg"
                - "image/gif"
                - "image/webp"
                - "image/svg+xml"
                - "image/bmp"
                - "image/tiff"
            - $formkit: text
              name: url
              label: 图片链接（点击将跳转）
              placeholder: 图片链接
              value: ""
    - group: header
      label: 顶栏
      formSchema:
        - $formkit: select
          name: showLogo
          label: 是否展示 logo
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: select
          name: showTitle
          label: 是否展示网站标题
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: select
          name: showSearch
          label: 是否展示搜索栏
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
    - group: footer
      label: 页脚
      formSchema:
        - $formkit: text
          name: icpNumber
          label: 工信部备案号
          placeholder: 如：豫ICP备XXX号
          value: ""
        - $formkit: text
          name: psnNumber
          label: 网安备案号
          placeholder: 如：豫公网安备XXX号
          value: ""
        - $formkit: text
          name: subCopyright
          label: 版权声明副说明
          placeholder: 如：since 2020 - present
          value: ""
    - group: friendshipLink
      label: 友链
      formSchema:
        - $formkit: select
          name: showFriendshipLinks
          label: 是否展示友链
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: repeater
          name: links
          label: 链接
          value: []
          children:
            - $formkit: text
              name: label
              label: 网站名称
              placeholder: 如：GOTAB百宝箱
              value: ""
              validation: "required"
            - $formkit: text
              name: url
              label: 网站地址
              placeholder: 如：https://www.gotab.cn
              value: ""
              validation: "required"
            - $formkit: attachment
              name: icon
              id: friendship_link_icon
              key: friendship_link_icon
              label: 网站图标（非必填）
              placeholder: 网站图标
              value: ""
    - group: authorInfo
      label: 博主简介
      formSchema:
        - $formkit: select
          name: showAuthorInfo
          label: 是否展示博主简介
          value: true
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
        - $formkit: select
          name: backgroundHeightType
          label: 区域内容高度
          value: fit
          id: backgroundHeightType
          key: backgroundHeightType
          options:
            - label: 适应内容大小
              value: fit
            - label: 全屏
              value: screen
        - $formkit: attachment
          name: avatar
          id: author_info_avatar
          key: author_info_avatar
          label: 头像
          placeholder: 头像
          value: ""
        - $formkit: text
          name: name
          label: 名称
          placeholder: 如：doxwant
          value: "佚名"
        - $formkit: textarea
          name: description
          rows: 3
          label: 描述（换行将开启打字机的切换效果）
          placeholder: 如：我是 XX，一个拥有多年经验的创意设计师和开发人员，在这里可以了解
          value: "欢迎访问我的个人博客，我将在这里与你分享更多精彩内容"
        - $formkit: number
          name: descriptionOpacity
          label: 描述透明度，全屏高度时替换为下指示箭头透明度（%）：0-100
          placeholder: 如：75
          value: 75
          step: 1
          min: 0
          max: 100
        - $formkit: repeater
          name: links
          label: 三方平台链接或个人其他主页
          value: []
          children:
            - $formkit: text
              name: label
              label: 网站名称（非必填）
              placeholder: 如：GOTAB百宝箱
              value: ""
            - $formkit: text
              name: url
              label: 网站地址
              placeholder: 如：https://www.gotab.cn
              value: ""
              validation: "required"
            - $formkit: attachment
              name: icon
              id: author_info_other_homepage_icon
              key: author_info_other_homepage_icon
              label: 网站图标（非必填）
              placeholder: 网站图标
              value: ""
        - $formkit: select
          name: backgroundType
          label: 背景类型
          value: color
          id: backgroundType
          key: backgroundType
          options:
            - label: 自定义颜色/渐变色
              value: color
            - label: 自定义图片
              value: image
            - label: 视频动画
              value: video
            - label: 禁用
              value: disable
        - $formkit: text
          if: "$get(backgroundType).value === color"
          key: background
          id: background
          name: background
          label: 背景颜色（支持渐变色 css ）
          placeholder: 如：linear-gradient(45deg,#03A9F4,#00ff5042)
          value: "linear-gradient(45deg,#03A9F4,#00ff5042)"
          validation: "required"
        - $formkit: attachment
          if: "$get(backgroundType).value === image"
          name: backgroundImage
          id: author_info_background_image
          key: author_info_background_image
          label: 背景图片（没有背景颜色时生效）
          placeholder: 背景图片
          value: ""
          validation: "required"
          accepts:
            - "image/png"
            - "image/jpeg"
            - "image/gif"
            - "image/webp"
            - "image/svg+xml"
            - "image/bmp"
            - "image/tiff"
        - $formkit: attachment
          if: "$get(backgroundType).value === video"
          name: backgroundVideo
          id: author_info_background_video
          key: author_info_background_video
          label: 背景视频/动画
          placeholder: 背景视频/动画
          value: ""
          validation: "required"
          accepts:
            - "video/mp4"
        - $formkit: color
          name: fontColor
          id: fontColor
          key: fontColor
          label: 字体颜色
          value: "#ffffff"
        - $formkit: number
          name: blur
          label: 背景模糊像素（px）：0-32
          placeholder: 如：0
          value: 0
          step: 1
          min: 0
          max: 32
        - $formkit: number
          name: brightness
          label: 背景亮度（%）：0-100
          placeholder: 如：100
          value: 100
          step: 1
          min: 0
          max: 100
    - group: moments
      label: 瞬间
      formSchema:
        - $formkit: select
          name: showMoments
          label: 是否在首页展示
          value: false
          options:
            - label: 开启
              value: true
            - label: 关闭
              value: false
